{
 "title": "Smartdiet",
 "time": { "from": "2026-03-24T09:39:14.124Z", "to": "2026-03-24T21:39:14.124Z" },
 "panels": [
  {
   "title": "Product Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"product-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eureka Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"eureka-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendation Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"recommendation-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"postgres-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"config-server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}