spring:
  application:
    name: product-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 5000

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/